FROM golang:1.16-alpine

WORKDIR /app

ENV CONFIG=docker

COPY . /app

RUN go get github.com/githubnemo/CompileDaemon
RUN go mod download

#EXPOSE 5000

ENTRYPOINT CompileDaemon --build="go build -o main cmd/main.go" --command=./main