DROP TABLE IF EXISTS emails CASCADE;
DROP TABLE IF EXISTS addresses CASCADE;
DROP EXTENSION IF EXISTS citext CASCADE;
DROP EXTENSION IF EXISTS pg_trgm CASCADE;
DROP EXTENSION IF EXISTS btree_gist CASCADE;
DROP EXTENSION IF EXISTS "uuid-ossp" CASCADE;