DROP TABLE IF EXISTS emails CASCADE;
DROP EXTENSION IF EXISTS citext CASCADE;
DROP EXTENSION IF EXISTS pg_trgm CASCADE;
DROP EXTENSION IF EXISTS btree_gist CASCADE;
DROP EXTENSION IF EXISTS "uuid-ossp" CASCADE;
DROP FUNCTION IF EXISTS emails_tsvector_trigger;
DROP TRIGGER IF EXISTS tsvectorupdate ON emails;