package constants

const (
	SERVER_PORT  = "SERVER_PORT"
	GRPC_PORT    = "GRPC_PORT"
	METRICS_PORT = "METRICS_PORT"

	NATS_URL       = "NATS_URL"
	CLUSTER_ID     = "CLUSTER_ID"
	NATS_CLIENT_ID = "NATS_CLIENT_ID"

	MAIL_SERVICE   = "MAIL_SERVICE"
	REDIS_URL      = "REDIS_URL"
	REDIS_PASSWORD = "REDIS_PASSWORD"

	POSTGRES_HOST     = "POSTGRES_HOST"
	POSTGRES_PORT     = "POSTGRES_PORT"
	POSTGRES_USER     = "POSTGRES_USER"
	POSTGRES_PASSWORD = "POSTGRES_PASSWORD"
	POSTGRES_DB       = "POSTGRES_DB"
	POSTGRES_SSL      = "POSTGRES_SSL"

	JAEGER_HOST = "JAEGER_HOST"

	MAIL_PORT     = "MAIL_PORT"
	MAIL_HOST     = "MAIL_HOST"
	MAIL_USERNAME = "MAIL_USERNAME"
	MAIL_PASSWORD = "MAIL_PASSWORD"
)
